config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  resources :capitals
  resources :attractions
  resources :countries
  resources :users

  root             'sessions#new'
  get 'attractions'    => 'attractions#index'
  get 'countries'   => 'countries#index'
  get 'capitals' => 'capitals#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/capital.rb
class Capital < ApplicationRecord
  belongs_to :country
end

app/controllers/capitals_controller.rb
class CapitalsController < ApplicationController
  before_action :logged_in_user
  before_action :set_capital, only: [:show, :edit, :update, :destroy]

  # GET /capitals
  # GET /capitals.json
  def index
    @capitals = Capital.all
  end

  # GET /capitals/1
  # GET /capitals/1.json
  def show
  end

  # GET /capitals/new
  def new
    @capital = Capital.new
  end

  # GET /capitals/1/edit
  def edit
    @countries = Country.all
  end

  # POST /capitals
  # POST /capitals.json
  def create
    @capital = Capital.new(capital_params)

    respond_to do |format|
      if @capital.save
        format.html { redirect_to @capital, notice: 'Capital was successfully created.' }
        format.json { render :show, status: :created, location: @capital }
      else
        format.html { render :new }
        format.json { render json: @capital.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capitals/1
  # PATCH/PUT /capitals/1.json
  def update
    respond_to do |format|
      if @capital.update(capital_params)
        format.html { redirect_to @capital, notice: 'Capital was successfully updated.' }
        format.json { render :show, status: :ok, location: @capital }
      else
        format.html { render :edit }
        format.json { render json: @capital.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capitals/1
  # DELETE /capitals/1.json
  def destroy
    @capital.destroy
    respond_to do |format|
      format.html { redirect_to capitals_url, notice: 'Capital was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capital
      @capital = Capital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capital_params
      params.require(:capital).permit(:name, :population, :country_id)
    end
end

app/helpers/capitals_helper.rb
module CapitalsHelper
end

app/views/capitals/_form.html.erb
<%= form_with(model: capital, local: true) do |form| %>
  <% if capital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(capital.errors.count, "error") %> prohibited this capital from being saved:</h2>

      <ul>
        <% capital.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4 my_form">
      <%= form_for(@capital) do |form| %>
        <%= form.label "Назва" %>
        <%= form.text_field :name, class: "form-control" %>

        <%= form.label "Населення" %>
        <%= form.number_field :population, class: "form-control" %>

        <%= form.label "Країна" %>
        <%= form.collection_select(:country_id, @countries, :id, :name, {}, { :class => "form-control" }) %>

        <%= form.submit "ОК", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/capitals/edit.html.erb
<h1>Редагування столиці</h1>

<div class="form_container">
  <%= render 'form', capital: @capital %>
  <div class="ref_container">
    <%= link_to 'Детальніше', @capital %> |
    <%= link_to 'Назад', capitals_path %>
  </div>
</div>

app/views/capitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Столиці</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Назва</th>
      <th scope="col">Населення</th>
      <th scope="col">Країна</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @capitals.each_with_index do |capital, index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= capital.name %></td>
        <td><%= capital.population %></td>
        <td><%= capital.country.name %></td>
        <td><%= link_to 'Детальніше', capital %></td>
        <td><%= link_to 'Редагувати', edit_capital_path(capital) %></td>
        <td><%= link_to 'Видалити', capital, method: :delete, data: { confirm: 'Ви впевнені?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="addNewItemLink">
  <%= link_to 'Додати нову столицю', new_capital_path %>
</div>

app/views/capitals/new.html.erb
<h1>Нова столиця</h1>

<div class="form_container">
  <%= render 'form', capital: @capital %>
  <div class="ref_container">
    <%= link_to 'Назад', capitals_path %>
  </div>
</div>

app/views/capitals/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @capital.name %></h1>

<table class="table table-bordered table-hover">
  <tbody>
      <tr>
        <td scope="row"><strong>Назва</strong></td>
        <td><%= @capital.name %></td>
      </tr>
      <tr>
        <td scope="row"><strong>Населення</strong></td>
        <td><%= @capital.population %></td>
      </tr>
      <tr>
        <td scope="row"><strong>Країна</strong></td>
        <td><%= Country.find(@capital.country_id).name %></td>
      </tr>
  </tbody>
</table>

<p><%= link_to 'Редагувати', edit_capital_path(@capital) %></p>
<p><%= link_to 'Видалити', @capital, method: :delete, data: { confirm: 'Ви впевнені?' } %></p>
<p><%= link_to 'Назад', capitals_path %></p>