config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  resources :capitals
  resources :attractions
  resources :countries
  resources :users

  root             'sessions#new'
  get 'attractions'    => 'attractions#index'
  get 'countries'   => 'countries#index'
  get 'capitals' => 'capitals#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/country.rb
class Country < ApplicationRecord
  validates :location, length: { maximum:  100}
  has_many :attractions
  has_one :capital
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :logged_in_user
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :location, :language, :currency)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country, local: true) do |form| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4 my_form">
      <%= form_for(@country) do |form| %>
        <%= form.label "Назва" %>
        <%= form.text_field :name, class: "form-control" %>

        <%= form.label "Місцезнаходження" %>
        <%= form.text_field :location, class: "form-control" %>

        <%= form.label "Мова" %>
        <%= form.text_field :language, class: "form-control" %>

        <%= form.label "Валюта" %>
        <%= form.text_field :currency, class: "form-control" %>

        <%= form.submit "ОК", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Редагування країни</h1>

<div class="form_container">
  <%= render 'form', country: @country %>
  <div class="ref_container">
    <%= link_to 'Детальніше', @country %> |
    <%= link_to 'Назад', countries_path %>
  </div>
</div>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Країни</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Назва</th>
      <th scope="col">Місцезнаходження</th>
      <th scope="col">Мова</th>
      <th scope="col">Валюта</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each_with_index do |country, index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= country.name %></td>
        <td><%= country.location %></td>
        <td><%= country.language %></td>
        <td><%= country.currency %></td>
        <td><%= link_to 'Детальніше', country %></td>
        <td><%= link_to 'Редагувати', edit_country_path(country) %></td>
        <td><%= link_to 'Видалити', country, method: :delete, data: { confirm: 'Ви впевнені?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="addNewItemLink">
  <%= link_to 'Додати країну', new_country_path %>
</div>

app/views/countries/new.html.erb
<h1>Нова країна</h1>

<div class="form_container">
  <%= render 'form', country: @country %>
  <div class="ref_container">
    <%= link_to 'Назад', countries_path %>
  </div>
</div>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @country.name %></h1>

<table class="table table-bordered table-hover">
  <tbody>
      <tr>
        <td scope="row"><strong>Назва</strong></td>
        <td><%= @country.name %></td>
      </tr>
      <tr>
        <td scope="row"><strong>Місцезнаходження</strong></td>
        <td><%= @country.location %></td>
      </tr>
      <tr>
        <td scope="row"><strong>Мова</strong></td>
        <td><%= @country.language %></td>
      </tr>
      <tr>
        <td scope="row"><strong>Валюта</strong></td>
        <td><%= @country.currency %></td>
      </tr>
  </tbody>
</table>

<p><%= link_to 'Редагувати', edit_country_path(@country) %></p>
<p><%= link_to 'Видалити', @country, method: :delete, data: { confirm: 'Ви впевнені?' } %></p>
<p><%= link_to 'Назад', countries_path %></p>