config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  resources :capitals
  resources :attractions
  resources :countries
  resources :users

  root             'sessions#new'
  get 'attractions'    => 'attractions#index'
  get 'countries'   => 'countries#index'
  get 'capitals' => 'capitals#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
<div class="container-fluid">
  <div class="row">
    <div class="col-md-7">
      <div class="collapse navbar-collapse" id="site-nav">
        <ul class="nav navbar-nav">

          <% if logged_in? %>
            <li><%= link_to "Пам'ятки природи", attractions_path %></li>
            <li><%= link_to "Країни", countries_path %></li>
            <li><%= link_to "Столиці", capitals_path %></li>
            <li><%= link_to "Вийти", logout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Зареєструватися", signup_path %></li>
            <li><%= link_to "Увійти", login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Пам'ятки природи</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>