config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  resources :capitals
  resources :attractions
  resources :countries
  resources :users

  root             'sessions#new'
  get 'attractions'    => 'attractions#index'
  get 'countries'   => 'countries#index'
  get 'capitals' => 'capitals#index'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :logged_in_user
  before_action :set_attraction, only: [:show, :edit, :update, :destroy]

  # GET /attractions
  # GET /attractions.json
  def index
    @attractions = Attraction.all
  end

  # GET /attractions/1
  # GET /attractions/1.json
  def show
  end

  # GET /attractions/new
  def new
    @attraction = Attraction.new
  end

  # GET /attractions/1/edit
  def edit
    @countries = Country.all
  end

  # POST /attractions
  # POST /attractions.json
  def create
    @attraction = Attraction.new(attraction_params)

    respond_to do |format|
      if @attraction.save
        format.html { redirect_to @attraction, notice: 'Attraction was successfully created.' }
        format.json { render :show, status: :created, location: @attraction }
      else
        format.html { render :new }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attractions/1
  # PATCH/PUT /attractions/1.json
  def update
    respond_to do |format|
      if @attraction.update(attraction_params)
        format.html { redirect_to @attraction, notice: 'Attraction was successfully updated.' }
        format.json { render :show, status: :ok, location: @attraction }
      else
        format.html { render :edit }
        format.json { render json: @attraction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attractions/1
  # DELETE /attractions/1.json
  def destroy
    @attraction.destroy
    respond_to do |format|
      format.html { redirect_to attractions_url, notice: 'Attraction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attraction
      @attraction = Attraction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attraction_params
      params.require(:attraction).permit(:name, :description, :country_id)
    end
end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_with(model: attraction, local: true) do |form| %>
  <% if attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attraction.errors.count, "error") %> prohibited this attraction from being saved:</h2>

      <ul>
        <% attraction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4 my_form">
      <%= form_for(@attraction) do |form| %>
        <%= form.label "Назва" %>
        <%= form.text_field :name, class: "form-control" %>

        <%= form.label "Опис" %>
        <%= form.text_area :description, class: "form-control" %>

        <%= form.label "Країна" %>
        <%= form.collection_select(:country_id, @countries, :id, :name, {}, { :class => "form-control" }) %>

        <%= form.submit "ОК", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/attractions/edit.html.erb
<h1>Редагування пам'ятки природи</h1>

<div class="form_container">
  <%= render 'form', attraction: @attraction %>
  <div class="ref_container">
    <%= link_to 'Детальніше', @attraction %> |
    <%= link_to 'Назад', attractions_path %>
  </div>
</div>

app/views/attractions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Пам'ятки природи</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Назва</th>
      <th scope="col">Опис</th>
      <th scope="col">Країна</th>
      <th colspan="7"></th>
    </tr>
  </thead>

  <tbody>
    <% @attractions.each_with_index do |attraction, index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= attraction.name %></td>
        <td><%= attraction.description %></td>
        <td><%= attraction.country.name %></td>
        <td><%= link_to 'Детальніше', attraction %></td>
        <td><%= link_to 'Редагувати', edit_attraction_path(attraction) %></td>
        <td><%= link_to 'Видалити', attraction, method: :delete, data: { confirm: 'Ви впевнені?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="addNewItemLink">
  <%= link_to 'Додати нову пам\'ятку природи', new_attraction_path %>
</div>

app/views/attractions/new.html.erb
<h1>Нова пам'ятка природи</h1>

<div class="form_container">
  <%= render 'form', attraction: @attraction %>
  <div class="ref_container">
    <%= link_to 'Назад', attractions_path %>
  </div>
</div>

app/views/attractions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @attraction.name %></h1>

<table class="table table-bordered table-hover">
  <tbody>
      <tr>
        <td scope="row"><strong>Назва</strong></td>
        <td><%= @attraction.name %></td>
      </tr>
      <tr>
        <td scope="row"><strong>Опис</strong></td>
        <td><%= @attraction.description %></td>
      </tr>
      <tr>
        <td scope="row"><strong>Країна</strong></td>
        <td><%= Country.find(@attraction.country_id).name %></td>
      </tr>
  </tbody>
</table>

<p><%= link_to 'Редагувати', edit_attraction_path(@attraction) %></p>
<p><%= link_to 'Видалити', @attraction, method: :delete, data: { confirm: 'Ви впевнені?' } %></p>
<p><%= link_to 'Назад', attractions_path %></p>